name: Deploy Hugo Site

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, review_requested]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 hugo -y
      - name: Checkout Notes
        uses: actions/checkout@v3
        with:
          path: notes
      - name: Checkout Hugo Site
        uses: actions/checkout@v3
        with:
          repository: hattivatt/hugo_rpgs
          token: ${{ secrets.GH_PAT }}
          path: hugosite
          submodules: 'recursive'
      - name: Checkout Obsidian to Hugo converter
        uses: actions/checkout@v3
        with:
          repository: devidw/obsidian-to-hugo
          path: obsidian-to-hugo
      - name: Checkout Site
        uses: actions/checkout@v3
        with:
          repository: hattivatt/hattivatt.github.io
          path: site
      - name: Generate Site From Notes
        run: |
          pwd
          ls ./hugosite/themes/eureka
          hugo version
          mkdir ./hugosite/content/docs/bluetides
          python3 obsidian-to-hugo/src --obsidian-vault-dir=./notes --hugo-content-dir=./hugosite/content/docs/bluetides
          cd hugosite
          hugo -d ../site
      - name: Push generated site
        run: |
          cd site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
