name: Deploy Hugo Site

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, review_requested]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 -y
          wget https://github.com/gohugoio/hugo/releases/download/v0.98.0/hugo_0.98.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.98.0_Linux-64bit.deb
          sudo apt-get install -f -y
      - name: Checkout Notes
        uses: actions/checkout@v3
        with:
          path: notes
      - name: Checkout Hugo Site
        uses: actions/checkout@v3
        with:
          repository: hattivatt/hugo_rpgs
          token: ${{ secrets.GH_PAT }}
          path: hugosite
          submodules: 'recursive'
      - name: Checkout Obsidian to Hugo converter
        uses: actions/checkout@v3
        with:
          repository: devidw/obsidian-to-hugo
          path: obsidian-to-hugo
      - name: Checkout Site
        uses: actions/checkout@v3
        with:
          repository: hattivatt/hattivatt.github.io
          path: site
          persist-credentials: false
          fetch-depth: 0
      - name: Generate Site From Notes
        run: |
          hugo version
          mkdir ./hugosite/content/docs/bluetides
          rm -rf ./notes/Templates
          ls -la obsidian-to-hugo/src/
          python3 obsidian-to-hugo/src/obsidian_to_hugo --obsidian-vault-dir=./notes --hugo-content-dir=./hugosite/content/docs
          cd hugosite
          hugo -d ../site
      - name: Push generated site
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: 'site'
          destination-github-username: 'hattivatt'
          destination-repository-name: 'hattivatt.github.io'
          user-email: github-actions@github.com
          target-branch: main
          #      - name: Push generated site
          #        run: |
          #          cd site
          #          git config user.name github-actions
          #          git config user.email github-actions@github.com
          #          git remote set-url origin https://PAT:${{ secrets.GH_PAT }}@github.com/hattivatt/hattivatt.github.io
          #          git add .
          #          git commit -m "generated"
          #          git push
